dist: xenial
language: python

# See aws s3 ls s3://travis-python-archives/binaries/ubuntu/16.04/x86_64/
python:
  - "nightly"
  - "pypy3.5"
  - "pypy2.7-5.10.0"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

cache: pip

services:
  - mysql

install:
  - pip install -U pip
  - pip install -U mock coverage pytest pytest-cov codecov

env:
  global:
    - TESTDB=travis.cnf

before_script:
  - "mysql --help"
  - "mysql --print-defaults"
  - "mysql -e 'create database mysqldb_test charset utf8mb4;'"

script:
  - pip install -e .
  - pytest --cov ./MySQLdb

after_succes:
  - codecov

# vim: sw=2 ts=2 sts=2
